name:                kpp-tool
version:             0.1.0.0
github:              "quytelda/kpp-tool"
license:             BSD-3-Clause
author:              "Quytelda Kahja"
maintainer:          "quytelda@tamalin.org"
copyright:           "Copyright 2023 Quytelda Kahja"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quytelda/kpp-tool#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 3
- base64 >= 0.4.2 && < 2.0
- bytestring >= 0.11
- containers >= 0.6
- JuicyPixels >= 3.3 && < 4
- xml-conduit >= 1.9 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  kpp-tool-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kpp-tool
    when:
    - condition: false
      other-modules: Paths_kpp_tool

tests:
  kpp-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kpp-tool
