{-# LANGUAGE FlexibleInstances   #-}
{-# LANGUAGE OverloadedStrings   #-}
{-# LANGUAGE RecordWildCards     #-}
{-# LANGUAGE ScopedTypeVariables #-}

{-|
Module      : Kpp.App
Description : Application Logic
Copyright   : (c) Quytelda Kahja, 2024
License     : BSD-3-Clause

This module contains logic related to the command-line interface,
including argument parsing, runtime configuration, and version/help
information.
-}
module Kpp.App where

import           Conduit
import           Control.Applicative
import           Control.Exception
import           Control.Monad
import           Control.Monad.Reader
import           Control.Monad.State
import           Data.Bifunctor
import           Data.Either
import           Data.Map.Strict           (Map)
import qualified Data.Map.Strict           as Map
import           Data.Maybe
import           Data.Text                 (Text)
import qualified Data.Text                 as T
import qualified Data.Text.IO              as TIO
import           Data.Version
import           Prettyprinter
import           Prettyprinter.Render.Text
import           System.Console.GetOpt
import           System.Exit

import           Kpp.Common
import           Kpp.Param
import           Kpp.Preset
import           Kpp.Resource

import qualified Paths_kpp_tool

-- | The kpp-tool version, exported from the Paths module
-- automatically generated by Cabal.
kppToolVersion :: Version
kppToolVersion = Paths_kpp_tool.version

--------------------------------------------------------------------------------
-- Argument Parsing

-- | A type for argument parsing errors.
data RuntimeError = RuntimeError String
                  | ArgumentError String
  deriving (Eq, Show)

instance Exception RuntimeError

-- | Try to break a list at the first occurence of some delimiter,
-- dropping the delimiter from the result. If no delimiter is found,
-- Nothing is returned.
breakOn :: Eq a => a -> [a] -> Maybe ([a], [a])
breakOn c = go []
  where
    go xs (y:ys) | c /= y    = go (y:xs) ys
                 | otherwise = Just (reverse xs, ys)
    go _ _                   = Nothing

-- | Split a `Prelude.String` on the first comma which is not escaped
-- with backslash.
splitOnComma :: String -> (String, String)
splitOnComma []              = ([], [])
splitOnComma (',' : cs)      = ([], cs)
splitOnComma ('\\' : c : cs) = first (c :) $ splitOnComma cs
splitOnComma (c : cs)        = first (c :) $ splitOnComma cs

commaSep :: String -> [String]
commaSep [] = []
commaSep xs = uncurry (:) . second commaSep . splitOnComma $ xs

-- | FromArgument is a class for types that can be parsed from a
-- `Prelude.String` argument to a CLI option, e.g.
-- @--some-flag=ARGUMENT@.
class FromArgument a where
  fromArgument :: MonadThrow m => String -> m a

  -- | This is a type hint to be displayed in help output and error
  -- messages. The default is @"VALUE"@.
  --
  -- The `String` is wrapped in a `Const` functor here so we can use a
  -- phantom type to select the correct instance without providing an
  -- actual value (using ScopedTypeVariables).
  argInfo :: Const String a
  argInfo = Const "VALUE"

fromArgumentOptional :: (FromArgument a, MonadThrow m) => Maybe String -> m (Maybe a)
fromArgumentOptional = traverse fromArgument

instance FromArgument String where
  fromArgument = pure
  argInfo = Const "STRING"

instance FromArgument Text where
  fromArgument = pure . T.pack
  argInfo = Const "STRING"

instance FromArgument ParamValue where
  fromArgument arg = case breakOn ':' arg of
    Just ("untyped",  val) -> Unknown  <$> pure (T.pack val)
    Just ("string",   val) -> String   <$> pure (T.pack val)
    Just ("internal", val) -> Internal <$> pure (T.pack val)
    Just ("binary",   val) -> Binary   <$> decodeBase64 (T.pack val)
    _                      -> throwM $ ArgumentError $
      "expected TYPE:VALUE, but got " <> show arg
  argInfo = Const "TYPE:VALUE"

instance (FromArgument k, FromArgument a) => FromArgument (k, a) where
  fromArgument arg = case breakOn '=' arg of
    Just (key, val) -> (,) <$> fromArgument key <*> fromArgument val
    Nothing         -> throwM $ ArgumentError $
      "expected KEY=VALUE, but got " <> arg
  argInfo = Const "KEY=VALUE"

instance (Ord k, FromArgument k, FromArgument a) => FromArgument (Map k a) where
  fromArgument = fmap Map.fromList . traverse fromArgument . commaSep
  argInfo = Const "KEY=VALUE[,...]"

-- | Something that can be converted to an `ArgDescr`.
class ToArgDescr a where
  toArgDescr :: a -> ArgDescr Command

instance ToArgDescr Command where
  toArgDescr s = NoArg s

instance FromArgument a => ToArgDescr (a -> Command) where
  toArgDescr f = ReqArg (fromArgument >=> f) (getConst (argInfo :: Const String a))

--------------------------------------------------------------------------------
-- CLI Interface

-- We receive a stream of commands from the CLI interface. Each
-- command has a flag and possibly an argument. Each command executes
-- a function which takes a preset, performs some action (possibly
-- with IO), and returns the possibly modified preset.
--
-- However, some commands need information besides just the Preset
-- data structure. For example, --sync-name needs to know the source
-- file name so it can set the preset name appropriately. This
-- information should be available in a RunConfig data structure.

-- Each command corresponds uniquely to a set of command line
-- switches, so therefore it should be possible to derive an OptDescr
-- from a Command or build an OptDescr with a Command.

-- If a command requires an argument of type `a`, its type should be
-- `Command a`. If the argument is optional, it should have type
-- `Command (Maybe a)`. If it takes no argument, the type should be
-- either `Command ()` or `Command Void` (not sure which yet).

-- However, not all arguments fit into this paradigm. For example, the
-- --overwrite command shouldn't be executed in a particular order -
-- it's effects only take place after the full pipeline has completed.

--------------------------------------------------------------------------------
-- Commands

type Command = StateT Preset (ReaderT RunConfig IO) ()

runCommand :: Command -> RunConfig -> Preset -> IO ()
runCommand cmd rc preset = runReaderT (evalStateT cmd preset) rc

-- | Save a `Resource` to file. An optional output path can be
-- provided; otherwise, the resource's filename property is used.
writeResource :: Maybe FilePath -> Resource -> Command
writeResource mpath resource = do
  path <- liftIO $ saveResource mpath resource

  -- If no output path was specified, we inform the user where the
  -- output was written.
  Flags{..} <- lift $ asks rcFlags
  unless (flagQuiet || isJust mpath) $
    liftIO $ putStrLn $ "Wrote resource to: " <> path

cmdGetName :: Command
cmdGetName = gets presetName >>= liftIO . TIO.putStrLn

cmdSetName :: Text -> Command
cmdSetName = modify . setPresetName

cmdOutput :: FilePath -> Command
cmdOutput path = do
  preset <- get
  liftIO $ runConduitRes $ presetToPng preset .| write
  where
    write = case path of
      "-" -> stdoutC
      _   -> sinkFile path

cmdInfo :: Command
cmdInfo = do
  preset <- get
  liftIO $ putDoc (pretty preset)
  liftIO $ putChar '\n'

cmdGetParam :: Text -> Command
cmdGetParam key = do
  preset <- get
  case lookupParam key preset of
    Just val -> liftIO $ putDoc (pretty val) *> putChar '\n'
    Nothing  -> throwM $ RuntimeError $ "no such parameter: " <> T.unpack key

cmdSetParam :: (Text, ParamValue) -> Command
cmdSetParam = modify' . uncurry insertParam

cmdExtract :: Map Text Text -> Command
cmdExtract opts = do
  let mpath = T.unpack <$> Map.lookup "path" opts
      lookupResource preset =
        (Map.lookup "name" opts >>= flip lookupResourceByName preset) <|>
        (Map.lookup "file" opts >>= flip lookupResourceByFile preset) <|>
        (Map.lookup "md5"  opts >>= flip lookupResourceByMD5  preset)

  preset <- get
  case lookupResource preset of
    Just resource -> writeResource mpath resource
    Nothing       -> throwM $ RuntimeError $
      "extract: no matching resource found"

commands :: [OptDescr Command]
commands = [ Option "n" ["get-name"]
             (toArgDescr cmdGetName)
             "Print a preset's metadata name."
           , Option "N" ["set-name"]
             (toArgDescr cmdSetName)
             "Change a preset's metadata name."
           , Option "i" ["info"]
             (toArgDescr cmdInfo)
             "Print a description of a preset."
           , Option "p" ["get-param"]
             (toArgDescr cmdGetParam)
             "Print the value of a single parameter."
           , Option "o" ["output"]
             (toArgDescr cmdOutput)
             "Write a preset to file (or '-' for stdout)."
           , Option "P" ["set-param"]
             (toArgDescr cmdSetParam)
             "Set the value of a parameter.\n\
             \TYPE can be 'string', 'internal', or 'binary'.\n\
             \For binary parameters, VALUE should be encoded in base-64."
           ]

data Flags = Flags
  { flagHelp    :: Bool
  , flagVersion :: Bool
  , flagQuiet   :: Bool
  } deriving (Eq, Show)

defaultFlags :: Flags
defaultFlags = Flags
  { flagHelp    = False
  , flagVersion = False
  , flagQuiet   = False
  }

flagOptions :: [OptDescr (Flags -> Flags)]
flagOptions = [ Option "h" ["help"]
                (NoArg $ \fs -> fs { flagHelp = True })
                "Display help and usage information."
              , Option "v" ["version"]
                (NoArg $ \fs -> fs { flagVersion = True })
                "Display version information."
              , Option "q" ["quiet"]
                (NoArg $ \fs -> fs { flagQuiet = True })
                "Supress unnecessary output."
              ]

data RunConfig = RunConfig
  { rcInputFile :: Maybe FilePath
  , rcFlags     :: Flags
  , rcCommands  :: [Command]
  }

-- | Command Line Options
options :: [OptDescr (Either (Flags -> Flags) Command)]
options = (fmap . fmap) Left  flagOptions <>
          (fmap . fmap) Right commands

parseArgs :: MonadThrow m => [String] -> m RunConfig
parseArgs args = do
  let (flags, positionArgs, errs) = getOpt RequireOrder options args

  -- Handle parsing failures.
  -- Note: Only the first error is actually thrown.
  mapM_ (throwM . ArgumentError) errs

  return $ RunConfig
    { rcInputFile = listToMaybe positionArgs
    , rcFlags     = foldr ($) defaultFlags (lefts flags)
    , rcCommands  = rights flags
    }

-- | `start` is the primary entrypoint of the application, intended to
-- be called by @main@. It expects a list of command line arguments.
start :: [String] -> IO ()
start args = do
  rc@RunConfig{..} <- parseArgs args

  when (flagHelp rcFlags) $ do
    putStrLn $ usageInfo "Usage: kpp-tool [OPTION]... [FILE]" options
    exitSuccess

  when (flagVersion rcFlags) $ do
    putStrLn $ "kpp-tool " <> showVersion kppToolVersion
    exitSuccess

  preset <- runConduitRes $
    maybe stdinC sourceFile rcInputFile
    .| pngToPreset

  runCommand (sequence_ rcCommands) rc preset
