{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}

{-|
Module      : Kpp.App
Description : Application Logic
Copyright   : (c) Quytelda Kahja, 2024
License     : BSD-3-Clause

This module contains logic related to the command-line interface,
including argument parsing, runtime configuration, and version/help
information.
-}
module Kpp.App
  ( start
  ) where

import           Conduit
import           Control.Applicative
import           Control.Monad
import           Control.Monad.Reader
import           Control.Monad.State
import           Data.Bifunctor
import           Data.Binary               hiding (get, put)
import qualified Data.ByteString           as BS
import qualified Data.ByteString.Lazy      as BL
import qualified Data.Map.Strict           as Map
import           Data.Maybe
import           Data.Text                 (Text)
import qualified Data.Text                 as T
import qualified Data.Text.IO              as TIO
import           Data.Version
import           Prettyprinter
import           Prettyprinter.Render.Text
import           System.Console.GetOpt
import           System.Exit
import           System.FilePath
import           System.IO

import           Kpp.Common
import           Kpp.Param
import           Kpp.Preset
import           Kpp.Resource

import qualified Paths_kpp_tool

-- | The kpp-tool version, exported from the Paths module
-- automatically generated by Cabal.
kppToolVersion :: Version
kppToolVersion = Paths_kpp_tool.version

--------------------------------------------------------------------------------
-- Argument Parsing

breakOn :: Eq a => a -> [a] -> Maybe ([a], [a])
breakOn c = go []
  where
    go xs (y:ys) | c /= y    = go (y:xs) ys
                 | otherwise = Just (reverse xs, ys)
    go _ _                   = Nothing

-- | Split a `Prelude.String` on the first comma which is not escaped
-- with backslash.
splitOnComma :: String -> (String, String)
splitOnComma []              = ([], [])
splitOnComma (',' : cs)      = ([], cs)
splitOnComma ('\\' : c : cs) = first (c :) $ splitOnComma cs
splitOnComma (c : cs)        = first (c :) $ splitOnComma cs

commaSep :: String -> [String]
commaSep [] = []
commaSep xs = uncurry (:) . second commaSep . splitOnComma $ xs

-- | FromArgument is a class for types that can be parsed from a
-- `Prelude.String` argument to a CLI option, e.g.
-- @--some-flag=ARGUMENT@.
class FromArgument a where
  fromArgument :: MonadThrow m => String -> m a

fromArgumentOptional :: (FromArgument a, MonadThrow m) => Maybe String -> m (Maybe a)
fromArgumentOptional marg = case marg of
  Just arg -> Just <$> fromArgument arg
  Nothing -> pure Nothing

instance FromArgument String where
  fromArgument = pure

instance FromArgument Text where
  fromArgument = pure . T.pack

instance FromArgument ParamValue where
  fromArgument arg = case breakOn ':' arg of
    Just ("untyped",  val) -> Unknown  <$> pure (T.pack val)
    Just ("string",   val) -> String   <$> pure (T.pack val)
    Just ("internal", val) -> Internal <$> pure (T.pack val)
    Just ("binary",   val) -> Binary   <$> decodeBase64 (T.pack val)
    _                      -> throwM $ ParseException $
      "expected TYPE:VALUE, but got " <> show arg

instance (FromArgument k, FromArgument a) => FromArgument (k, a) where
  fromArgument arg = case breakOn '=' arg of
    Just (key, val) -> (,) <$> fromArgument key <*> fromArgument val
    Nothing         -> throwM $ ParseException $
      "expected KEY=VALUE, but got " <> arg

instance (Ord k, FromArgument k, FromArgument a) => FromArgument (Map.Map k a) where
  fromArgument = fmap Map.fromList . traverse fromArgument . commaSep

-- | `start` is the primary entrypoint of the application, intended to
-- be called by @main@. It expects a list of command line arguments.
start :: [String] -> IO ()
start args = undefined
