{-# LANGUAGE FlexibleInstances   #-}
{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE OverloadedLists     #-}
{-# LANGUAGE OverloadedStrings   #-}
{-# LANGUAGE RecordWildCards     #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications    #-}
{-# LANGUAGE ViewPatterns        #-}

{-|
Module      : Kpp.App
Description : Application Logic
Copyright   : (c) Quytelda Kahja, 2026
License     : BSD-3-Clause

This module contains logic related to the command-line interface,
including argument parsing, runtime configuration, and version/help
information.
-}
module Kpp.App
  ( -- * Entrypoint
    run

    -- * Version
  , kppToolVersion

    -- * Settings
  , parseSettings
  , Settings(..)
  , RunSettings(..)
  , Action(..)
  , ResourceSpec(..)
  ) where

import           Conduit
import           Control.Applicative
import           Control.Monad
import           Control.Monad.Reader
import           Control.Monad.State
import           Data.Bifunctor
import qualified Data.ByteString.Base64    as Base64
import qualified Data.ByteString.Lazy      as BL
import           Data.Maybe
import           Data.Text                 (Text)
import qualified Data.Text                 as T
import           Data.Text.Encoding        (encodeUtf8)
import qualified Data.Text.IO              as TIO
import           Data.Version
import           Mangrove
import qualified Mangrove.TextParser       as TP
import           Mangrove.Unix
import           Prettyprinter
import           Prettyprinter.Render.Text
import           System.FilePath

import           Kpp.Param
import           Kpp.Preset
import           Kpp.Resource

import qualified Paths_kpp_tool

-- | The kpp-tool version, exported from the Paths module
-- automatically generated by Cabal.
kppToolVersion :: Version
kppToolVersion = Paths_kpp_tool.version

-- | A resource specifier that points to a particular resource by
-- name, filename, or MD5 checksum.
data ResourceSpec
  = RSName !Text
  | RSFile !Text
  | RSCsum !Text
  deriving (Show)

-- | An operation that can be performed with a preset.
data Action
  = Output FilePath
  | Info
  | GetName
  | SetName Text
  | SyncName
  | ListParams
  | GetParam Text
  | SetParam Text ParamValue
  | ListResources
  | Extract ResourceSpec (Maybe FilePath)
  | ExtractAll (Maybe FilePath)
  | Embed FilePath Text (Maybe Text) (Maybe Text)
  | GetIcon FilePath
  | SetIcon FilePath
  deriving (Show)

-- | Break a string around the first occurence of some character. If
-- the string contains the character, the result is a tuple containing
-- everything before and everything after that character. If the
-- character does not occur in the string, the result is 'Nothing'.
breakOnChar :: Char -> Text -> Maybe (Text, Text)
breakOnChar c text =
  case T.break (== c) text of
    (pre, T.uncons -> Just (_, post)) -> Just (pre, post)
    _                                 -> Nothing

-- | Parse a 'SetParam' action from a parameter a string in the form
-- @KEY=TYPE:VALUE@.
parseSetParam :: ParseTree SubScheme Action
parseSetParam = subparameter TextParser
  { parserHint = "KEY=TYPE:VALUE"
  , parserRun = \text ->
      case breakOnChar '=' text of
        Just (key, val) ->
          case breakOnChar ':' val of
            Just ("notype", value) -> Right $ SetParam key $ Unknown value
            Just ("string", value) -> Right $ SetParam key $ String value
            Just ("internal", value) -> Right $ SetParam key $ Internal value
            Just ("binary", value) ->
              bimap T.pack (SetParam key . Binary)
              $ Base64.decode
              $ encodeUtf8 value
            _ -> Left "invalid type specifier"
        _ -> Left "expected \"KEY=\""
  }

-- | Parse an 'Extract' action.
parseExtract :: ParseTree SubScheme Action
parseExtract = Extract
  <$> parseResourceSpec
  <*> optional subopt_dest
  where
    parseResourceSpec =
      suboption "name" (RSName <$> defaultParser) <|>
      suboption "file" (RSFile <$> defaultParser) <|>
      suboption "md5"  (RSCsum <$> defaultParser)
    subopt_dest =
      suboption "dest" TP.parseFilePath

-- | Parse an 'Embed' action.
parseEmbed :: ParseTree SubScheme Action
parseEmbed = Embed
  <$> suboption "path" defaultParser
  <*> suboption "type" defaultParser
  <*> optional (suboption "name" defaultParser)
  <*> optional (suboption "file" defaultParser)

-- | A 'TextParser' for file paths.
pathParser :: TextParser FilePath
pathParser = defaultParser {parserHint="PATH"}

-- | Parse an option corresponding to any 'Action'.
parseAction :: ParseTree UnixScheme Action
parseAction = asum @[]
  [ option [LongFlag "output", ShortFlag 'o']
    "Write preset data to file (\"-\" for stdout)"
    $ fmap Output
    $ subparameter pathParser
  , option [LongFlag "info", ShortFlag 'i']
    "Print a summary of preset settings"
    $ pure Info
  , option [LongFlag "get-name", ShortFlag 'n']
    "Print preset name"
    $ pure GetName
  , option [LongFlag "set-name", ShortFlag 'N']
    "Change preset name"
    $ fmap SetName
    $ subparameter defaultParser
  , option [LongFlag "sync-name", ShortFlag 'S']
    "Synchronize preset name with the filename"
    $ pure SyncName
  , option [LongFlag "list-params", ShortFlag 'l']
    "Print a table of parameters and their values"
    $ pure ListParams
  , option [LongFlag "get-param", ShortFlag 'p']
    "Look up the value of a parameter"
    $ fmap GetParam
    $ subparameter defaultParser {parserHint="KEY"}
  , option [LongFlag "set-param", ShortFlag 'P']
    "Set the value of a parameter"
    $ parseSetParam
  , option [LongFlag "list-resources", ShortFlag 'r']
    "List embedded resources"
    $ pure ListResources
  , option [LongFlag "extract", ShortFlag 'x']
    "Extract an embedded resources"
    $ parseExtract
  , option [LongFlag "extract-all", ShortFlag 'X']
    "Extract all embedded resources"
    $ fmap ExtractAll
    $ optional $ subparameter defaultParser {parserHint = "DIR"}
  , option [LongFlag "embed", ShortFlag 'e']
    "Insert or replace an embedded resource"
    $ parseEmbed
  , option [LongFlag "get-icon", ShortFlag 'c']
    "Extract the preset icon image"
    $ fmap GetIcon
    $ subparameter pathParser
  , option [LongFlag "set-icon", ShortFlag 'C']
    "Replace the preset icon image"
    $ fmap SetIcon
    $ subparameter pathParser
  ]

-- | Settings for normal program operations.
data RunSettings = RunSettings
  { rsQuiet     :: Bool
  , rsOverwrite :: Bool
  , rsActions   :: [Action]
  , rsInputFile :: Maybe FilePath
  } deriving (Show)

parseRunSettings :: ParseTree UnixScheme RunSettings
parseRunSettings = RunSettings
  <$> opt_quiet
  <*> opt_overwrite
  <*> some parseAction
  <*> prm_presetFile
  where
    opt_quiet =
      switch ["--quiet", "-q"]
      "Supress unnecessary output"
    opt_overwrite =
      switch ["--overwrite", "-O"]
      "Overwrite the input file after processing"

parsePathLike :: TextParser (Maybe FilePath)
parsePathLike = TextParser
  { parserHint = "PRESET_FILE"
  , parserRun = \case
      "-"  -> pure Nothing
      path -> pure $ Just $ T.unpack path
  }

prm_presetFile :: UnixParser (Maybe FilePath)
prm_presetFile = parameter parsePathLike

-- | Settings for one of several possible runtime modes.
data Settings
  = DumpXmlMode (Maybe FilePath) (Maybe FilePath)
  | RunMode RunSettings
  deriving (Show)

-- | Parse all program settings
parseSettings :: ParseTree UnixScheme Settings
parseSettings = withHelp
  $ opt_version
  <|> cmd_dumpXml
  <|> RunMode <$> parseRunSettings
  where
    withHelp =
      addHelpOptions [LongFlag "help", ShortFlag 'h']
      "Display help and usage information"
    opt_version =
      requestOption [LongFlag "version", ShortFlag 'v']
      "Display version information"
      versionRequest
    prm_outputFile = parameter parsePathLike { parserHint = "OUTPUT_FILE" }
    cmd_dumpXml =
      command ["dump-xml"]
      "Dump a preset's XML settings to standard output"
      $ DumpXmlMode <$> (prm_presetFile <|> pure Nothing)
                    <*> (prm_outputFile <|> pure Nothing)

--------------------------------------------------------------------------------
-- Program Logic

lookupResource :: ResourceSpec -> Preset -> Maybe Resource
lookupResource (RSName name) = lookupResourceByName name
lookupResource (RSFile file) = lookupResourceByFile file
lookupResource (RSCsum csum) = lookupResourceByMD5 csum

writeResource :: Maybe FilePath -> Resource -> ActionM ()
writeResource mpath resource = do
  path <- liftIO $ saveResource mpath resource

  -- If no output path was specified, we inform the user where the
  -- output was written.
  quiet <- asks rsQuiet
  unless (quiet || isJust mpath) $
    liftIO $ putStrLn $ "Wrote resource to: " <> path

type ActionM = ReaderT RunSettings (StateT Preset IO)

runActionM :: ActionM a -> RunSettings -> Preset -> IO Preset
runActionM ma = execStateT . runReaderT ma

runAction :: Action -> ActionM ()
runAction (Output path) = do
  preset <- get
  liftIO $ runConduitRes $ presetToPng preset .| write
  where
    write = case path of
      "-" -> stdoutC
      _   -> sinkFile path
runAction Info = do
  preset <- get
  liftIO $ putDoc (pretty preset) *> putChar '\n'
runAction GetName =
  get >>= liftIO . TIO.putStrLn . presetName
runAction (SetName name) =
  modify' (setPresetName name)
runAction SyncName = do
  mInputPath <- asks rsInputFile
  case mInputPath of
    Just path -> modify' $ setPresetName $ T.pack $ takeBaseName path
    Nothing   -> fail "--sync-name requires an input path"
runAction ListParams = do
  Preset{..} <- get
  liftIO $ putDoc (prettyParams presetParams) *> putChar '\n'
runAction (SetParam key value) =
  modify' (insertParam key value)
runAction (GetParam key) = do
  preset <- get
  case lookupParam key preset of
    Just value -> liftIO $ putDoc (pretty value) *> putChar '\n'
    Nothing    -> fail $ "no such parameter: " <> T.unpack key
runAction ListResources = do
  Preset{..} <- get
  liftIO $ putDoc (prettyResources embeddedResources) *> putChar '\n'
runAction (Extract spec mpath) = do
  preset <- get
  case lookupResource spec preset of
    Just resource -> writeResource mpath resource
    Nothing       -> fail "extract: no matching resource found"
runAction (ExtractAll mdir) = do
  resources <- gets embeddedResources
  forM_ resources $ \resource ->
    writeResource (makePath resource <$> mdir) resource
  where
    makePath Resource{..} dir = dir </> takeFileName (T.unpack resourceFile)
runAction (Embed rPath rType mName mFile) = do
  resource <- liftIO $ loadResource rPath rType mName mFile
  modify' (insertResource resource)
runAction (GetIcon path) = do
  gets presetIcon >>= liftIO . BL.writeFile path
runAction (SetIcon path) = do
  icon <- liftIO $ BL.readFile path
  get >>= setPresetIcon icon >>= put

-- | Run the program with the provided runtime settings.
run :: Settings -> IO ()
run settings = do
  case settings of
    DumpXmlMode mInPath mOutPath ->
      let src = maybe stdinC sourceFile mInPath
          dst = maybe stdoutC sinkFile mOutPath
      in runConduitRes $ src .| extractSettings .| dst
    RunMode rs@RunSettings{..} -> do
      let pipeline = mapM_ runAction rsActions
          src = maybe stdinC sourceFile rsInputFile
          dst = maybe stdoutC sinkFileCautious rsInputFile
      preset <- runConduitRes $ src .| pngToPreset
      preset' <- runActionM pipeline rs preset

      -- We wait until processing is complete before overwriting the
      -- original file. Since reading the input and writing the output
      -- are in separate ResourceT blocks, this should avoid
      -- conflicts.
      when rsOverwrite $
        runConduitRes $ presetToPng preset' .| dst
